# Generated by Django 4.0.6 on 2022-07-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('index', models.PositiveBigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Country Name')),
                ('languages', models.CharField(max_length=200, verbose_name='Country Languages')),
                ('population', models.CharField(max_length=200, verbose_name='Country Population')),
                ('sha1', models.CharField(max_length=200, verbose_name='Country Encrypt Name')),
            ],
            options={
                'db_table': 'countries',
            },
        ),
    ]
